### ISSUE TITLE
Prevent user navigation on all platforms.

### ISSUE THREAD

**Issue by quadrupleslap** [quadrupleslap/tether#1]
We need to prevent the user from using reload/back/forward/etc. shortcuts or context menu items.

- [x] macOS
- [x] Windows
- [x] Linux / Other

**Comment by quadrupleslap** [comment]
I think that this depends on https://bugs.webkit.org/show_bug.cgi?id=140207 but I'm not sure.

**Comment by fullreset** [comment]
MacOS also needs help here -- unless i misunderstand the meaning of the checkboxes in the OP -- because the context menu shows the reload option, and a reload will result in a blank screen if you haven't navigated to a actual server yet ...

**Comment by quadrupleslap** [comment]
Sorry about that, macOS is the *only* one that needs help here! It's a current bug in Apple's new WebKit wrapper (they deprecated the old frameworks on macOS and iOS that had support for this kind of stuff, but didn't add many of the features to this unified one.)

**Comment by fullreset** [comment]
I agree, it's not worth switching back -- and in any case this snippet gets rid of the context menu on OSX painlessly:
```
document.addEventListener("contextmenu", function(e) {
    e.preventDefault();
    return false;
});
```
The existence of a workaround is good enough, although of course this breaks if you navigate to a 3rd party site, in which case the app should probably inject this snippet into the page. Perhaps just a note about this issue and this pseudo-fix in the `README` is enough.

**Comment by quadrupleslap** [comment]
Fixed! Thanks for the workaround!
