### ISSUE TITLE
URL overrides.

### ISSUE THREAD

**Issue by quadrupleslap** [quadrupleslap/tether#10]
Add a `Handler` function:

```rust
fn serve(&mut self, url: &str) -> Option<Response> { None }
```

This should allow the user to send web-assembly, images, etc. without creating a web server. I do not know how this would be implemented on any platform.

**Comment by quadrupleslap** [comment]
It doesn't look like this is possible without a web server. But is it worth making a crate that would make an ephemeral server with a simple API, or are existing web servers simple enough?

**Comment by quadrupleslap** [comment]
I think that the way to go is to.add a proper Getting Started guide, and a good example of opening a web server on an ephemeral port.

**Comment by fullreset** [comment]
For what it's worth I vote for keeping things light -- if users needs a web server, then they can do so via random crates or their own code.

**Comment by quadrupleslap** [comment]
Closing because now there's an example of using a server to serve binary files!
