### ISSUE TITLE
[Feature request] devtools

### ISSUE THREAD

**Issue by mradke** [quadrupleslap/tether#19]
It would be nice if we had the option to open the web view devtools to inspect if anything went wrong while initializing the given resources.

**Comment by rumanbsl** [comment]
Any update on this?

**Comment by quadrupleslap** [comment]
I'll try adding this now, but what OS are you on? Linux is much easier to work with than Windows.

**Comment by rumanbsl** [comment]
I am on mac. I guess, it won't be a trouble.

**Comment by quadrupleslap** [comment]
Super-old issue, but added in 0.3.0.

**Comment by mradke** [comment]
Actually I'm using OS X :-) 
Sorry for beeing unresponsive, my notification were a little messed up for quite some time.

I'll give it a try! Thanks 👍
