### ISSUE TITLE
borderless is not configurable on Linux

### ISSUE THREAD

**Issue by asmarcz** [quadrupleslap/tether#24]
Hi, I noticed that borderless option doesn't take any effect on Linux. I think it is caused by

https://github.com/quadrupleslap/tether/blob/4e1a63bbd91d29905cb1173c05adac2faf6187b2/native/gtk.c#L154

as the option doesn't seem to be taken into account as it is on Windows and (presumably, can't test) on Mac.

**Comment by quadrupleslap** [comment]
Replacing that line with

```rust
if (opts.borderless) gtk_window_set_decorated(window, FALSE);
```

should be enough, right?

**Comment by asmarcz** [comment]
https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-decorated states: "By default, windows are decorated with a title bar, resize controls, etc."

I guess it should be enough.

**Comment by quadrupleslap** [comment]
Okay, done! :)

Sorry, I should probably test things with a non-tiling wm.

**Comment by asmarcz** [comment]
Thanks, I would love to contribute on this in the future if I get it to work. :D :)
