### ISSUE TITLE
Extra terminal window opened in Windows

### ISSUE THREAD

**Issue by ameykshirsagar** [quadrupleslap/tether#28]
Excellent work on tether.
However in Windows whenever I run a cargo build and execute the binary, an extra terminal opens along with the app. How can I disable that and simply open the web application??

**Comment by quadrupleslap** [comment]
I think you just have to add

```
#![windows_subsystem = "windows"]
```

at the top of your `main.rs`.

**Comment by ameykshirsagar** [comment]
Thank you
