### ISSUE TITLE
Best way to access window handle off the main thread?

### ISSUE THREAD

**Issue by amiraeva** [quadrupleslap/tether#30]
I have an application built on `tether 0.2.1` which made use of the `tether::dispatch` function to schedule the execution of some js on the window thread, from a different thread. In migrating to the newest version, I can't seem to find an obvious way to mimic that same functionality now that `tether::dispatch` doesn't pass a handle to the window, nor is it easy to squirrel one away since its `!Send + !Sync`. Any suggestions on how to do this?

Thanks for this wonderful library BTW!

**Comment by quadrupleslap** [comment]
The best way right now would be to use thread-local variables. I'd appreciate ideas on how to make it nicer, though.

**Comment by amiraeva** [comment]
Thanks for getting back to me! I didn't think to use a thread local, I think that'll do for now. 

The only long term solution I can think of is to consider giving `tether::dispatch` a handle to the window like in the old `0.2` API, or somehow allow the creation of a `Send + Sync` window handle (if that's even possible with how `tether` works under the hood).

Thanks again!
