### ISSUE TITLE
Export OpenGL context to be rendered on.

### ISSUE THREAD

**Issue by Yatekii** [quadrupleslap/tether#34]
Hey!

Do you think it would be possible to export the OpenGL/Vulkan context such that I can draw on and then render the webui on?
Maybe it would also be a possibility to have a canvas and draw on that, but I don't know if that is sandboxed or not.
I can also try and implement this myself, but if you had some pointers that would be great.

Best,
Yatekii

**Comment by quadrupleslap** [comment]
I have no idea how you'd do that, sorry. There's a lot of sandbxoing going on with the WIndows 10 web view, too, so I'm pretty sure it's impossible.
