### ISSUE TITLE
webkit2gtk 2.22 seems to be required, not 2.8

### ISSUE THREAD

**Issue by oefd** [quadrupleslap/tether#35]
Trying to build tether on Ubuntu 16.04 (which has webkit2gtk 2.20) an error is encountered:

```
cargo:warning=gtk.c: In function ‘message_received’:
cargo:warning=gtk.c:38:5: error: unknown type name ‘JSCValue’
cargo:warning=     JSCValue *val = webkit_javascript_result_get_js_value(result);
cargo:warning=     ^
```

And in [the webkit docs](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-javascript-result-get-js-value) it would appear that function and indeed the entire `JSCValue` type didn't come to exist until version 2.22 of webkit2gtk.

**Comment by quadrupleslap** [comment]
Sorry for the late response, and thanks!
