### ISSUE TITLE
Differences vs. web-view, webview

### ISSUE THREAD

**Issue by WrinklyNinja** [quadrupleslap/tether#7]
web-view and webview are two existing Rust libraries that provide webview access, it would be useful to potential users if the readme mentioned what differentiates tether from them.

**Comment by quadrupleslap** [comment]
The main difference is the nicer API (in my opinion!), but there are a bunch of other differences as well.

| Feature | Tether | Libraries Based on [zserge/webview](https://github.com/zserge/webview) |
|-|-|-|
| Windows Engine | **EdgeHTML (Microsoft Edge)** | MSHTML (Internet Explorer)
| macOS Text Editing Keyboard Shortcuts | **Work** | Don't Work |
| Linux Tiling Window Managers | **Tile** | Float (Incorrect Behavior) |
| String Escaping | **Builtin** | External Libraries |
| Dialogs | External Libraries | **Builtin** |
| Number of Windows | One | Platform-Dependent |
| iOS + Android Support | Planned™️ | ??? |

Which of these do you think are relevant, and did I miss anything?

**Comment by WrinklyNinja** [comment]
I think they're all relevant, and I wasn't aware of most of them, thanks. Probably the most relevant difference for me is that tether requires the application to be a UWP application on Windows (and so restricts it to Windows 10) while the zserge/webview-based libraries don't: this is related to the HTML engine, but it's probably worth highlighting separately. Some users won't care about the Windows 10 restriction, while others could without realising it exists until they've already invested...

**Comment by quadrupleslap** [comment]
Oh, whoops! You're right, I forgot about minimum system requirements.

**Comment by quadrupleslap** [comment]
Thanks again! I added the system requirements and the comparison to the README.
